
batch_size: 64
n_epochs: 20
learning_rate: 0.0003

policy_kwargs:
  act_fn_name: 'relu'
  net_arch: [32, 32]
  input_shape: 4
  output_shape: 1

reward_kwargs:
  l1_loss_weight: 1
  l2_loss_weight: 1

optimizer: adam
num_check_point_to_save: 10
device: cuda


